### ISSUE TITLE
GAP parameter file (water_intra_gap.xml) did not exist

### ISSUE THREAD

**Issue by leoil** [t-young31/gap-train#22]
Hello
I am running the `zn_h2o` example, and it gives this error. 
```
    raise IOError(f'GAP parameter file ({self.name}.xml) did not exist')
OSError: GAP parameter file (water_intra_gap.xml) did not exist 
```
Seems an extra `water_intra_gap.xml` is needed when the `train_inter()` function is called. 
Can this file be shared?
If so, may I have a copy of it.  I will not distribute the file.
I appreciate your help.

**Comment by t-young31** [comment]
Hi,

Thanks for pointing this out. I'm not sure if I can share/upload the .xml because of the GAP license, but I can add the script to generate it, which is added under [this](https://github.com/t-young31/gap-train/tree/update_example) branch. I've not tried it with the latest QUIP version however, so the train command may not work (it uses 2 and 3 body descriptors rather than a SOAP) 

Tom

**Comment by leoil** [comment]
Thanks! The new script works  fine on the latest QUIP version, and .xml is generated correctly.
