### ISSUE TITLE
Custom SOAP neighbours defaulting to last set specified

### ISSUE THREAD

**Issue by tristan-j-wood** [t-young31/gap-train#26]
Manually choosing SOAP neighbours for more than one element results in the neighbours for all atoms being the last specified neighbour list. For example:

    gap = gt.GAP(name=system_name, system=system, default_params=False)

    gap.params.soap['Zn'] = gt.GTConfig.gap_default_soap_params
    gap.params.soap['Zn']['cutoff'] = 4.0
    gap.params.soap['Zn']['other'] = ['H', 'S', 'N', 'C']

    gap.params.soap['C'] = gt.GTConfig.gap_default_soap_params
    gap.params.soap['C']['cutoff'] = 4.0
    gap.params.soap['C']['other'] = ['H', 'S', 'N']

Results in the following log output:

2021-07-20 17:29:12 comp0800 gaptrain.log[132662] INFO Adding SOAP:              Zn
2021-07-20 17:29:12 comp0800 gaptrain.log[132662] INFO with neighbours           ['H', 'S', 'N']
2021-07-20 17:29:12 comp0800 gaptrain.log[132662] INFO Adding SOAP:              C
2021-07-20 17:29:12 comp0800 gaptrain.log[132662] INFO with neighbours           ['H', 'S', 'N']

Thus meaning the 'gap.params.soap['Zn']['other'] = ['H', 'S', 'N', 'C']' neighbour list has been overwritten.

I can send example files if you want to reproduce the issue.

Tristan

**Comment by t-young31** [comment]
I _think_ we've talked about this before, but it's due to Python assigning complex objects by reference rather than by value. For simple things assignment is by value:
```
>>> a = 1
>>> b = a
>>> b = 2
>>> a
1
```
but with lists and dicts etc. they may be expensive to copy so are assigned by reference and the original object will change if the new one is mutated e.g.:
```
>>> a = [0, 1]
>>> b = a
>>> b[0] = 1
>>> a
[1, 1]
```
The solution is to copy the thing:
```
>>> a = [0, 1]
>>> b = deepcopy(a)
>>> b[0] = 1
>>> a
[0, 1]
```
this isn't a bug, just a _feature_ of Python so I'm going to close the issue. Hopefully the above is useful!
